feat: テストを書く
matsuri-tech/endpoints-go pull request #13
Opened 2022-09-16 09:30 UTC by 0num4

qa マジック棒

@myuon endpoints-goにテストを書いたんですが、この関数で大丈夫かレビューしてほしいです。
文脈としては #11 を解消したくて #11 に対するテストを書く準備です

2022-09-16 10:27 UTC, myuon commented on endpoints_test.go
> +			if got := e.generateAPIListByFrontend(tt.args.version, tt.args.frontend); !reflect.DeepEqual(got, tt.want) {
このAPIはswagger用のやつじゃないのでこれに対してテスト書いても意味はない気がします。(別に書いてもらってもいいんですが)
swaggerを生成している関数の方を見るべきかと

2022-09-22 11:01 UTC, 0num4 commented
とりあえず正常系と#11 の修正のために使った実値のテストだけ入れています。

2022-09-26 06:33 UTC, myuon requested changes

2022-09-26 06:33 UTC, myuon commented on endpoints_test.go
> +var m2mCoreRealValueFieldsStruct = fields{
public repositoryにプロダクト関連のものを入れないでください。一般的なものでお願いします。

2022-09-26 06:45 UTC, 0num4 commented on endpoints_test.go
> +var m2mCoreRealValueFieldsStruct = fields{
確かに, 失礼しました

2022-10-18 06:21 UTC, closed without merging